services:
  - type: web
    name: buzz-in-server
    env: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
